[package]
name = "game_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.5"
reqwest = {version="0.11.*", features=["stream", "blocking"]}
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
tokio = {version= "1.*", features = ["macros", "rt-multi-thread"]}
